"use client";

import { useMemo, useState } from "react";
import { Check, ChevronRight, FileText, HeartHandshake, LockKeyhole, ShieldCheck } from "lucide-react";

const initial = { groomName: "", brideName: "", groomPhone: "", bridePhone: "", groomIncome: "", brideIncome: "", city: "", hasProperty: "", lgpd: false, truth: false, hipossuficiencia: false };
const fullName = (name: string) => /^\p{L}{3,}\s+\p{L}{2,}/u.test(name.trim());
const money = (value: string) => (Number(value.replace(/\D/g, "") || 0) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const cents = (value: string) => Number(value.replace(/\D/g, ""));

export default function Home() {
  const [eligible, setEligible] = useState<"" | "sim" | "nao">("");
  const [step, setStep] = useState(1);
  const [form, setForm] = useState(initial);
  const [protocol, setProtocol] = useState("");
  const [error, setError] = useState("");
  const [sending, setSending] = useState(false);
  const total = useMemo(() => cents(form.groomIncome) + cents(form.brideIncome), [form.groomIncome, form.brideIncome]);
  const update = (key: keyof typeof initial, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));

  async function submit() {
    setError(""); setSending(true);
    const response = await fetch("/api/registrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, groomIncomeCents: cents(form.groomIncome), brideIncomeCents: cents(form.brideIncome) }) });
    const data = await response.json();
    setSending(false);
    if (!response.ok) return setError(data.message || "Não foi possível enviar agora.");
    setProtocol(data.protocol);
  }

  return <main><header className="topbar"><a className="brand" href="/"><span className="brand-mark">CJ</span><span>Carvalhos de Justiça</span></a><nav><a className="nav-active" href="/">Inscrição</a><a href="/login">Acesso administrativo</a></nav></header><section className="shell"><aside className="intro"><div className="hero-photo" role="img" aria-label="Casal caminhando em um jardim arborizado"/><div className="eyebrow"><HeartHandshake size={16}/> casamento comunitário</div><h1>Comece seu novo capítulo.</h1><p>Faça sua inscrição para a triagem inicial do casamento civil gratuito. O preenchimento leva poucos minutos.</p><div className="assurance"><ShieldCheck size={22}/><span>Suas informações são tratadas com segurança e usadas apenas para esta finalidade.</span></div><div className="steps"><span className={step >= 1 ? "done" : ""}>1</span><i></i><span className={step >= 2 ? "done" : ""}>2</span><i></i><span className={step >= 3 ? "done" : ""}>3</span></div><small>Elegibilidade&nbsp;&nbsp; Dados do casal&nbsp;&nbsp; Declarações</small></aside><section className="form-card">{protocol ? <Success protocol={protocol}/> : eligible !== "sim" ? <Eligibility eligible={eligible} setEligible={setEligible}/> : step === 1 ? <CoupleForm form={form} update={update} next={() => setStep(2)}/> : step === 2 ? <Criteria form={form} update={update} back={() => setStep(1)} next={() => setStep(3)} total={total}/> : <Declarations form={form} update={update} back={() => setStep(2)} submit={submit} sending={sending} error={error}/>}</section></section></main>;
}

function Eligibility({ eligible, setEligible }: { eligible: "" | "sim" | "nao"; setEligible: (value: "sim" | "nao") => void }) { return <><span className="section-tag">etapa inicial</span><h2>Declaração de hipossuficiência</h2><p className="muted">Você se enquadra nos critérios para solicitar a declaração de hipossuficiência financeira para fins de casamento civil gratuito?</p><div className="choice-grid"><button className={eligible === "sim" ? "selected" : ""} onClick={() => setEligible("sim")}><Check/> Sim, prossiga com o cadastro</button><button className={eligible === "nao" ? "selected danger" : ""} onClick={() => setEligible("nao")}>Não, não me enquadro</button></div>{eligible === "nao" && <p className="notice">Este cadastro é destinado a pessoas que se enquadram nos critérios de hipossuficiência. Se tiver dúvidas, fale com a organização responsável.</p>}<div className="privacy-note"><LockKeyhole size={15}/> O envio não garante aprovação automática. A organização e o cartório conferirão informações e documentos.</div></> }

function CoupleForm({ form, update, next }: any) { const invalid = (form.groomName && !fullName(form.groomName)) || (form.brideName && !fullName(form.brideName)); return <><span className="section-tag">etapa 2 de 3</span><h2>Dados do casal</h2><p className="muted">Informe os dados básicos para a análise inicial.</p><div className="two-col"><Field label="Nome completo do noivo" value={form.groomName} set={(value:string) => update("groomName", value)} placeholder="Nome e sobrenome"/><PhoneField label="WhatsApp do noivo" value={form.groomPhone} set={(value:string) => update("groomPhone", value)}/><MoneyField label="Renda mensal do noivo" value={form.groomIncome} set={(value:string) => update("groomIncome", value)}/><Field label="Nome completo da noiva" value={form.brideName} set={(value:string) => update("brideName", value)} placeholder="Nome e sobrenome"/><PhoneField label="WhatsApp da noiva" value={form.bridePhone} set={(value:string) => update("bridePhone", value)}/><MoneyField label="Renda mensal da noiva" value={form.brideIncome} set={(value:string) => update("brideIncome", value)}/></div><label className="full-field">Cidade do casamento<input value={form.city} onChange={(event) => update("city", event.target.value)} placeholder="Sua cidade"/></label>{invalid && <p className="field-error">Informe nome e sobrenome. O primeiro nome deve ter pelo menos 3 letras.</p>}<button className="primary" disabled={!fullName(form.groomName) || !fullName(form.brideName) || !form.groomPhone || !form.bridePhone} onClick={next}>Continuar <ChevronRight size={18}/></button></> }

function Criteria({ form, update, back, next, total }: any) { return <><span className="section-tag">etapa 3 de 3</span><h2>Critérios de elegibilidade</h2><p className="muted">Para seguir, confirme as informações abaixo. O limite atual é de até 3 salários mínimos, configurável pela administração.</p><div className="summary"><span>Renda mensal do casal</span><strong>{(total / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></div><p className="question">Você ou seu(sua) futuro(a) cônjuge possuem imóvel próprio?</p><div className="choice-grid compact"><button className={form.hasProperty === "nao" ? "selected" : ""} onClick={() => update("hasProperty", "nao")}>Não</button><button className={form.hasProperty === "sim" ? "selected danger" : ""} onClick={() => update("hasProperty", "sim")}>Sim</button></div>{form.hasProperty === "sim" && <p className="notice">O cadastro seguirá como pendente para análise humana, pois este critério precisa ser conferido.</p>}<div className="actions"><button className="secondary" onClick={back}>Voltar</button><button className="primary" disabled={!form.hasProperty} onClick={next}>Continuar <ChevronRight size={18}/></button></div></> }

function Declarations({ form, update, back, submit, sending, error }: any) { const ok = form.lgpd && form.truth && form.hipossuficiencia; return <><span className="section-tag">confirmação</span><h2>Termos e declarações</h2><p className="muted">Leia com atenção e marque os termos para finalizar seu cadastro.</p><div className="checks"><CheckLine checked={form.truth} set={(value:boolean) => update("truth", value)} text="Declaro, sob as penas da lei, que todas as informações prestadas são verdadeiras."/><CheckLine checked={form.hipossuficiencia} set={(value:boolean) => update("hipossuficiencia", value)} text="Declaro que não possuo condições de arcar com as despesas do casamento civil sem prejuízo do meu sustento ou da minha família."/><CheckLine checked={form.lgpd} set={(value:boolean) => update("lgpd", value)} text="Li e aceito o tratamento dos meus dados para cadastro, análise de elegibilidade, contato e eventual encaminhamento ao cartório, conforme a LGPD."/></div>{error && <p className="field-error">{error}</p>}<p className="privacy-note"><LockKeyhole size={15}/> Ao enviar, serão registrados data, horário, IP, dispositivo e a versão do termo aceito.</p><div className="actions"><button className="secondary" onClick={back}>Voltar</button><button className="primary" disabled={!ok || sending} onClick={submit}>{sending ? "Enviando..." : "Enviar cadastro"} <ChevronRight size={18}/></button></div></> }

function Field({ label, value, set, placeholder }: { label: string; value: string; set: (value: string) => void; placeholder: string }) { return <label className="full-field">{label}<input value={value} onChange={(event) => set(event.target.value)} placeholder={placeholder}/></label> }
function MoneyField({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label className="full-field">{label}<input inputMode="numeric" value={value} onChange={(event) => set(money(event.target.value))} placeholder="R$ 0,00"/></label> }
function PhoneField({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { const mask = (input: string) => { const digits = input.replace(/\D/g, "").slice(0, 11); return digits.replace(/(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2"); }; return <label className="full-field">{label}<input inputMode="tel" value={value} onChange={(event) => set(mask(event.target.value))} placeholder="(16) 99999-9999"/></label> }
function CheckLine({ checked, set, text }: { checked: boolean; set: (value: boolean) => void; text: string }) { return <label className="checkline"><input type="checkbox" checked={checked} onChange={(event) => set(event.target.checked)}/><span>{text}</span></label> }
function Success({ protocol }: { protocol: string }) { return <div className="success"><div className="success-icon"><Check/></div><span className="section-tag">cadastro recebido</span><h2>Obrigada pelo envio.</h2><p className="muted">Seu protocolo é <strong>{protocol}</strong>. A equipe responsável fará a análise das informações e entrará em contato pelos canais informados.</p><div className="protocol"><FileText size={20}/><span>Guarde seu número de protocolo para acompanhamento.</span></div></div> }
