"use client";

import { useMemo, useState } from "react";
import { Check, ChevronRight, FileText, HeartHandshake, LockKeyhole, ShieldCheck } from "lucide-react";
const initial = { noivo: "", noiva: "", telefoneNoivo: "", telefoneNoiva: "", rendaNoivo: "", rendaNoiva: "", imovel: "", lgpd: false, verdade: false, hipossuficiencia: false };
const fullName = (name: string) => /^\p{L}{3,}\s+\p{L}{2,}/u.test(name.trim());
const money = (value: string) => {
  const digits = value.replace(/\D/g, "");
  return (Number(digits || 0) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
};
const moneyNumber = (value: string) => Number(value.replace(/\D/g, "")) / 100;

export default function Home() {
  const [eligible, setEligible] = useState<"" | "sim" | "nao">("");
  const [step, setStep] = useState(1); const [form, setForm] = useState(initial); const [sent, setSent] = useState(false);
  const rendaTotal = useMemo(() => moneyNumber(form.rendaNoivo) + moneyNumber(form.rendaNoiva), [form]);
  const update = (key: keyof typeof initial, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  return <main><header className="topbar"><a className="brand" href="/"><span className="brand-mark">CJ</span><span>Carvalhos de Justiça</span></a><nav><a className="nav-active" href="/">Inscrição</a><a href="/login">Acesso administrativo</a></nav></header><section className="shell"><aside className="intro"><div className="hero-photo" role="img" aria-label="Casal caminhando em um jardim arborizado"/><div className="eyebrow"><HeartHandshake size={16}/> casamento comunitário</div><h1>Comece seu novo capítulo.</h1><p>Faça sua inscrição para a triagem inicial do casamento civil gratuito. O preenchimento leva poucos minutos.</p><div className="assurance"><ShieldCheck size={22}/><span>Suas informações são tratadas com segurança e usadas apenas para esta finalidade.</span></div><div className="steps"><span className={step >= 1 ? "done" : ""}>1</span><i></i><span className={step >= 2 ? "done" : ""}>2</span><i></i><span className={step >= 3 ? "done" : ""}>3</span></div><small>Elegibilidade&nbsp;&nbsp; Dados do casal&nbsp;&nbsp; Declarações</small></aside><section className="form-card">{sent ? <Success /> : eligible !== "sim" ? <Eligibility eligible={eligible} setEligible={setEligible} /> : step === 1 ? <CoupleForm form={form} update={update} next={() => setStep(2)} /> : step === 2 ? <Criteria form={form} update={update} back={() => setStep(1)} next={() => setStep(3)} rendaTotal={rendaTotal} /> : <Declarations form={form} update={update} back={() => setStep(2)} submit={() => setSent(true)} />}</section></section></main>;
}
function Eligibility({ eligible, setEligible }: { eligible: "" | "sim" | "nao"; setEligible: (v: "sim" | "nao") => void }) { return <><span className="section-tag">etapa inicial</span><h2>Declaração de hipossuficiência</h2><p className="muted">Você se enquadra nos critérios para solicitar a declaração de hipossuficiência financeira para fins de casamento civil gratuito?</p><div className="choice-grid"><button className={eligible === "sim" ? "selected" : ""} onClick={() => setEligible("sim")}><Check/> Sim, prossiga com o cadastro</button><button className={eligible === "nao" ? "selected danger" : ""} onClick={() => setEligible("nao")}>Não, não me enquadro</button></div>{eligible === "nao" && <p className="notice">Este cadastro é destinado a pessoas que se enquadram nos critérios de hipossuficiência. Se tiver dúvidas, fale com a organização responsável.</p>}<div className="privacy-note"><LockKeyhole size={15}/> O envio não garante aprovação automática. A organização e o cartório conferirão informações e documentos.</div></> }
function CoupleForm({ form, update, next }: any) { return <><span className="section-tag">etapa 2 de 3</span><h2>Dados do casal</h2><p className="muted">Informe os dados básicos para a análise inicial.</p><div className="two-col"><Field label="Nome completo do noivo" value={form.noivo} set={(v:string)=>update("noivo",v)} placeholder="Nome e sobrenome"/><PhoneField label="WhatsApp do noivo" value={form.telefoneNoivo} set={(v:string)=>update("telefoneNoivo",v)}/><MoneyField label="Renda mensal do noivo" value={form.rendaNoivo} set={(v:string)=>update("rendaNoivo",v)}/><Field label="Nome completo da noiva" value={form.noiva} set={(v:string)=>update("noiva",v)} placeholder="Nome e sobrenome"/><PhoneField label="WhatsApp da noiva" value={form.telefoneNoiva} set={(v:string)=>update("telefoneNoiva",v)}/><MoneyField label="Renda mensal da noiva" value={form.rendaNoiva} set={(v:string)=>update("rendaNoiva",v)}/></div><label className="full-field">Cidade do casamento<input placeholder="Sua cidade" /></label>{(form.noivo && !fullName(form.noivo) || form.noiva && !fullName(form.noiva)) && <p className="field-error">Informe nome e sobrenome. O primeiro nome deve ter pelo menos 3 letras.</p>}<button className="primary" disabled={!fullName(form.noivo) || !fullName(form.noiva) || !form.telefoneNoivo || !form.telefoneNoiva} onClick={next}>Continuar <ChevronRight size={18}/></button></> }
function Criteria({ form, update, back, next, rendaTotal }: any) { return <><span className="section-tag">etapa 3 de 3</span><h2>Critérios de elegibilidade</h2><p className="muted">Para seguir, confirme as informações abaixo. O limite atual é de até 3 salários mínimos, configurável pela administração.</p><div className="summary"><span>Renda mensal do casal</span><strong>{rendaTotal.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></div><p className="question">Você ou seu(sua) futuro(a) cônjuge possuem imóvel próprio?</p><div className="choice-grid compact"><button className={form.imovel === "nao" ? "selected" : ""} onClick={() => update("imovel", "nao")}>Não</button><button className={form.imovel === "sim" ? "selected danger" : ""} onClick={() => update("imovel", "sim")}>Sim</button></div>{form.imovel === "sim" && <p className="notice">O cadastro seguirá como pendente para análise humana, pois este critério precisa ser conferido.</p>}<div className="actions"><button className="secondary" onClick={back}>Voltar</button><button className="primary" disabled={!form.imovel} onClick={next}>Continuar <ChevronRight size={18}/></button></div></> }
function Declarations({ form, update, back, submit }: any) { const ok = form.lgpd && form.verdade && form.hipossuficiencia; return <><span className="section-tag">confirmação</span><h2>Termos e declarações</h2><p className="muted">Leia com atenção e marque os termos para finalizar seu cadastro.</p><div className="checks"><CheckLine checked={form.verdade} set={(v:boolean)=>update("verdade",v)} text="Declaro, sob as penas da lei, que todas as informações prestadas são verdadeiras."/><CheckLine checked={form.hipossuficiencia} set={(v:boolean)=>update("hipossuficiencia",v)} text="Declaro que não possuo condições de arcar com as despesas do casamento civil sem prejuízo do meu sustento ou da minha família."/><CheckLine checked={form.lgpd} set={(v:boolean)=>update("lgpd",v)} text="Li e aceito o tratamento dos meus dados para cadastro, análise de elegibilidade, contato e eventual encaminhamento ao cartório, conforme a LGPD."/></div><p className="privacy-note"><LockKeyhole size={15}/> Ao enviar, serão registrados data, horário, IP, dispositivo e a versão do termo aceito.</p><div className="actions"><button className="secondary" onClick={back}>Voltar</button><button className="primary" disabled={!ok} onClick={submit}>Enviar cadastro <ChevronRight size={18}/></button></div></> }
function Field({label,value,set,placeholder,type="text"}:{label:string,value:string,set:(v:string)=>void,placeholder:string,type?:string}) { return <label className="full-field">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label> }
function MoneyField({label,value,set}:{label:string,value:string,set:(v:string)=>void}) { return <label className="full-field">{label}<input inputMode="numeric" value={value} onChange={e=>set(money(e.target.value))} placeholder="R$ 0,00"/></label> }
function PhoneField({label,value,set}:{label:string,value:string,set:(v:string)=>void}) { const mask=(v:string)=>{const d=v.replace(/\D/g,"").slice(0,11);return d.replace(/(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2")};return <label className="full-field">{label}<input inputMode="tel" value={value} onChange={e=>set(mask(e.target.value))} placeholder="(16) 99999-9999"/></label> }
function CheckLine({checked,set,text}:{checked:boolean,set:(v:boolean)=>void,text:string}) { return <label className="checkline"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><span>{text}</span></label> }
function Success() { return <div className="success"><div className="success-icon"><Check/></div><span className="section-tag">cadastro recebido</span><h2>Obrigada pelo envio.</h2><p className="muted">Seu protocolo é <strong>CC-2026-0841</strong>. A equipe responsável fará a análise das informações e entrará em contato pelos canais informados.</p><div className="protocol"><FileText size={20}/><span>Guarde seu número de protocolo para acompanhamento.</span></div></div> }
function Admin() { const rows=[["CC-2026-0841","Amanda & Rafael","Aguardando análise","R$ 3.120,00"],["CC-2026-0840","Bianca & Lucas","Pendente de documentos","R$ 2.900,00"],["CC-2026-0839","Marina & João","Aprovado para continuar","R$ 2.640,00"]]; return <section className="admin-shell"><div className="admin-heading"><div><span className="section-tag">painel administrativo</span><h1>Visão geral da triagem</h1><p className="muted">Acompanhe cadastros, critérios e pendências em um só lugar.</p></div><button className="primary">Exportar relatório</button></div><div className="metrics"><Metric label="Cadastros recebidos" n="84"/><Metric label="Aguardando análise" n="18"/><Metric label="Aprovados" n="42"/><Metric label="Com alertas" n="9"/></div><section className="table-card"><div className="table-title"><h2>Cadastros recentes</h2><button className="secondary">Filtros</button></div><div className="data-table"><div className="head"><span>Protocolo</span><span>Casal</span><span>Status</span><span>Renda total</span></div>{rows.map(r=><div className="row" key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><em className={r[2].startsWith("Aprovado") ? "approved" : "pending"}>{r[2]}</em><span>{r[3]}</span></div>)}</div></section><p className="admin-foot"><LockKeyhole size={14}/> Acesso administrativo protegido. CPFs e documentos completos ficam disponíveis apenas na tela de detalhes do cadastro.</p></section> }
function Metric({label,n}:{label:string,n:string}) { return <article className="metric"><span>{label}</span><strong>{n}</strong><small>atualizado agora</small></article> }
